// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	provider2 "github.com/angelokurtis/terraform-provider-github/internal/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider"
)

// Injectors from wire_inj.go:

func NewProvider(ctx context.Context) (provider.Provider, func(), error) {
	gitHub := provider2.NewGitHub()
	return gitHub, func() {
	}, nil
}
